name: Build and Test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test-linux:
    strategy:
      fail-fast: true

    runs-on:
      - ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install nix
        uses: nixbuild/nix-quick-install-action@v30

      - name: nix cache
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}

      - name: set up nix shell
        run: nix-shell --command 'true'

      - name: make
        run: nix-shell --command 'make'

      - name: make test
        run: nix-shell --command 'make test'

      - name: end-to-end tests
        run: nix-shell --command 'python test-programs/runner.py'

      - name: examples
        run: nix-shell --command 'bash run-examples.sh'

      - name: build the stdlib
        run: nix-shell --command 'make -C standard clean && make -C standard'

      - name: test the stdlib
        run: nix-shell --command './standard/test_bin'

      - name: upload compiler binary
        uses: actions/upload-artifact@v2
        with:
          name: austral-linux-bin
          path: austral
          retention-days: 1

      - name: clean
        run: make clean

      - name: assert executable does not exist
        run: test ! -f austral
